[project]
name = "ffunrun"
version = "0.1.14"
description = "funrun"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "funshell>=1.0.19", "funutil>=1.0.48", "typer>=0.9.0",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[project.scripts]
funrun = "funrun.run:run_task"

[dependency-groups]
dev = [ "funbuild>=1.6.65", "pytest>=7.0.0",]

[tool.setuptools]
license-files = []

[tool.uv]
[[tool.uv.index]]
name = "packages-pypi"
url = "https://packages.aliyun.com/5fc5eb115dbd287006145e5f/pypi/funpy"

